# Base image for the frontend
FROM node:22-slim

# Set working directory
WORKDIR /frontend

# Copy package.json and package-lock.json separately for better caching
COPY package*.json ./

# Copy the rest of the application files
COPY . .

# Expose application port
EXPOSE 3000

# Install dependencies
RUN npm install

# Command to start the application
CMD ["npm", "run", "dev"]